### ISSUE TITLE
DAF python bug

### ISSUE THREAD

**Issue by annapaolagiancaspro** [xiaoyue10131748/Lalaine#1]
Hi

I was using Lalaine to perform the second step of DAF usage through the network traffic and call trace retrieved by previous step.
When I run this command "python analyze_log.py -d . -n 0" this is what comes out:

<img width="2560" alt="Screenshot 2023-04-13 at 14 33 30" src="https://user-images.githubusercontent.com/83175380/231759541-31d20c43-baf3-4734-bcd9-c75f3ce61e07.png">

and then after several lines:

<img width="1178" alt="Screenshot 2023-04-13 at 14 33 54" src="https://user-images.githubusercontent.com/83175380/231759637-9ed369bf-5b29-4c64-9861-bea6a0bbc2ef.png">

Can you help me?

Thank you in advance

**Comment by xiaoyue10131748** [comment]
It looks like the error when HarParse try to parse the network traffic. You may need to save the network traffic in har format to allow HarParse to correctly read.

**Comment by annapaolagiancaspro** [comment]
Thanks!
